### ISSUE TITLE
Error de pedido

### ISSUE THREAD

**Issue by Nidev-lab** [EloyPintos10/vikingo-cerveceria#1]
## Proceso

1. Me loguee con un usuario.
2. Seleccione algunos productos.
3. Ingrese al carrito y confirme mi pedido.

## Resultado esperado

Poder realizar mi pedido con exito.

## Resultado actual

Hay un error.

## Captura

![image](https://user-images.githubusercontent.com/53904695/228010270-13acdebf-2fc0-4c15-bd79-057c95873b04.png)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by EloyPintos10** [comment]
Listo Nico solucionado el tema del pedido!

**Comment by EloyPintos10** [comment]
Nico como estas? Acabo de terminar creo los issues que me marcaste del proyecto. Ya estaría funcionando la parte que me faltaba en pedidos. Gracias

Enviado desde mi iPhone

El 27 mar. 2023, a la(s) 13:57, Nico Gonzalez ***@***.***> escribió:

﻿

Proceso

  1.  Me loguee con un usuario.
  2.  Seleccione algunos productos.
  3.  Ingrese al carrito y confirme mi pedido.

Resultado esperado

Poder realizar mi pedido con exito.

Resultado actual

Hay un error.

Captura

[image]<https://user-images.githubusercontent.com/53904695/228010270-13acdebf-2fc0-4c15-bd79-057c95873b04.png>

Cualquier cosita pueden contactarme a ***@***.******@***.***> o por el slack de RollingCode
